### ISSUE TITLE
OSX:  Unable to find p4

### ISSUE THREAD

**Issue by mnsanghvi** [qoocku/magit-p4#2]
I get the following error when I try to run magit-p4-rebase (4 r)

```
  1 git … p4 rebase
/bin/sh: p4: command not found
Traceback (most recent call last):
  File "/opt/local/libexec/git-core/git-p4", line 3684, in <module>
    main()
  File "/opt/local/libexec/git-core/git-p4", line 3678, in main
    if not cmd.run(args):
  File "/opt/local/libexec/git-core/git-p4", line 3468, in run
    sync.run([])
  File "/opt/local/libexec/git-core/git-p4", line 3187, in run
    self.clientSpecDirs = getClientSpec()
  File "/opt/local/libexec/git-core/git-p4", line 882, in getClientSpec
    client_name = entry["Client"]
KeyError: 'Client'
```

When I use `p4.el` which seems to be required by `magit-p4` I do not get any such errors.  It is able to
find `/usr/local/bin/p4` and do everything that needs to get done.

Any thoughts and or suggestions ?  Are there any variables I need to set prior to using `magit-p4` ? 

Below is my configuration from `~/.emacs`

``` elisp
;;;;
;;;; P4.el -- Perforce integration
;;;;
(require 'p4)
(eval-after-load 'p4
    '(p4-set-p4-config "p4config"))

;;;;
;;;; magit setup
;;;;
(require 'magit)
(require 'magit-p4)  
(global-set-key (kbd "C-x g") 'magit-status)
(global-set-key (kbd "C-x M-g") 'magit-dispatch-popup)
```

**Comment by mnsanghvi** [comment]
Emacs version:  "GNU Emacs 24.5.1 (x86_64-apple-darwin15.4.0, NS apple-appkit-1404.46)
 of 2016-05-03 on msanghvi-mac"

**Comment by mnsanghvi** [comment]
The value of `exec-path` is given below:

``` emacs
("/opt/local/bin" "/opt/local/sbin" "/usr/local/bin" "/usr/local/java/default/bin" "/usr/local/maven/default/bin" "/usr/local/sbin" "/usr/bin" "/bin" "/usr/sbin" "/sbin" "/Applications/MacPorts/Emacs.app/Contents/MacOS/libexec" "/Applications/MacPorts/Emacs.app/Contents/MacOS/bin")
```

**Comment by mnsanghvi** [comment]
I managed to get it to work.  I had to install `exes-path-from-shell` from MELPA.

**Comment by lexa** [comment]
I'm glad that you found a workaround. It seems that problem is that PATH in emacs and PATH in your shell was different. I'm not sure what should be the proper solution for this issue. 

Should I add a dependency on exec-path-from-shell ?

**Comment by mnsanghvi** [comment]
I would not set a dependency on exec-path-from-shell, though I would
mention it in the README.md.

People start emacs differently, and for the people that start from within
Terminal.app or such, everything works fine
without exec-path-from-shell.  Hence it makes more sense to mention it in
the README.md.

cheers,

```
  mehul
```

On Mon, Jun 20, 2016 at 5:25 AM, lexa notifications@github.com wrote:

> I'm glad that you found a workaround. It seems that problem is that PATH
> in emacs and PATH in your shell was different. I'm not sure what should be
> the proper solution for this issue.
> 
> Should I add a dependency on exec-path-from-shell ?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/qoocku/magit-p4/issues/2#issuecomment-227092468, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABpYyNPWjnMVM9a6sUX8qoRK3LyKj_uiks5qNlx5gaJpZM4I5Szk
> .

## 

Mehul N. Sanghvi
email: mehul.sanghvi@gmail.com

**Comment by mnsanghvi** [comment]
This is working just fine with `exec-path-from-shell` installed so I am closing the issue.
