### ISSUE TITLE
Can't find version 12.0 of `p4`.

### ISSUE THREAD

**Issue by mdorman** [qoocku/magit-p4#6]
The latest I can find on marmalade is 11.0, and there are no tagged versions for melpa-stable.  This makes it uninstallable unless one wants to use the unstable melpa.

**Comment by lexa** [comment]
You can install p4-12.0 from regular melpa, as well as magit-p4.
If you are eager to use only stable packages, you can request p4 author to publish it on melpa-stable, then I can publish magit-p4 on melpa-stable.

P.S. I see you already requested p4 author to make a tagged release (https://github.com/gareth-rees/p4.el/issues/232 ).

**Comment by tarsius** [comment]
I just tagged `v1.2.0`.

Unfortunately p4 still does not tag releases, but there's nothing I can do about that.
