### ISSUE TITLE
Automatically submitting changes to Perforce

### ISSUE THREAD

**Issue by mnsanghvi** [qoocku/magit-p4#7]
I do the following in magit:

- stage a change (s)
- commit the change (C c)
- provide a comment for the commit and than `C-c C-c` out of it
- magit-p4-submit (S s)

At this point I am presented with a Perforce Change Specification buffer.  
I do a `C-x #` and get the following in the mini-buffer:

```
Submit template unchaged.  Submit anyway? (yes or no)
```

Is there anyway to skip this question and when I press `C-x #` magit-p4 just does the submit as requested ?

**Comment by qoocku** [comment]
I don't think so - "submit" just invokes `git-p4 submit` command with optional arguments. According to this page (https://git-scm.com/docs/git-p4) there is no option which could make it happen. I mean, one may always detect unchanged template and inject "yes" in such case but it requires some changes in the mod code ;)

**Comment by mnsanghvi** [comment]
I think this is what I used before 

```
git-p4.skipSubmitEditCheck=true
```

Will that work now ?   This is from [issue #3 ]

**Comment by tarsius** [comment]
> Will that work now ?

I don't know and assume you tried it yourself by now.
Closing (this package no longer has a maintainer).
