### ISSUE TITLE
Transfer attempt has expired

### ISSUE THREAD

**Issue by tarsius** [qoocku/magit-p4#8]
You tried to transfer this repository to me but by the time I saw that it had already expired.

Did we discuss this somewhere?

**Comment by tarsius** [comment]
ping @lexa

**Comment by lexa** [comment]
Hi @tarsius. Indeed I want to find a good owner for magit-p4. I can't maintain it anymore since I lost access to P4 server. I'm afraid that magit-p4 is going to deteriorate with time.

Are you interested in taking care of the project?

**Comment by tarsius** [comment]
No, or rather just in a very minimal way.

But I do maintain the emacs orphanage as part of the emacs mirror and that's a good place for packages at least getting some support.

- https://github.com/emacsmirror
- https://emacsmirror.net/
- https://github.com/emacsorphanage
- https://emacsmirror.net/stats/emacsorphanage.html

**Comment by tarsius** [comment]
I would fix a few defects that I spotted taking a quick look.

**Comment by lexa** [comment]
>I would fix a few defects that I spotted taking a quick look.

Thank you.

Do you still want me to transfer the project to you?

**Comment by tarsius** [comment]
Yes, I think that would be a good idea.

Please try to transfer to `emacsorphanage` instead. That didn't work in the past, but I think now it does. If it doesn't, then transfer to `tarsius` instead and I will then transfer it to `emacsorphanage`. Ping me here once you have initiated the transfer as I might not read my mail for a full day.

**Comment by lexa** [comment]
It seems that I don't have enough permissions to do it myself. I pinged @qoocku outside of Github, maybe he would find time to do the transfer.

**Comment by qoocku** [comment]
@tarsius - unfortunately i got "You don’t have the permission to create public repositories on emacsorphanage ". I'll try to tranfer to you instead.

**Comment by tarsius** [comment]
The repository has arrived! Thanks.

**Comment by tarsius** [comment]
And I pushed some fixes and cleanup.
